/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	v2 "Persona_CRD/pkg/apis/compute/v2"
	computev2 "Persona_CRD/pkg/client/applyconfiguration/compute/v2"
	scheme "Persona_CRD/pkg/client/clientset/versioned/scheme"
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PersonasGetter has a method to return a PersonaInterface.
// A group's client should implement this interface.
type PersonasGetter interface {
	Personas(namespace string) PersonaInterface
}

// PersonaInterface has methods to work with Persona resources.
type PersonaInterface interface {
	Create(ctx context.Context, persona *v2.Persona, opts v1.CreateOptions) (*v2.Persona, error)
	Update(ctx context.Context, persona *v2.Persona, opts v1.UpdateOptions) (*v2.Persona, error)
	UpdateStatus(ctx context.Context, persona *v2.Persona, opts v1.UpdateOptions) (*v2.Persona, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.Persona, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2.PersonaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.Persona, err error)
	Apply(ctx context.Context, persona *computev2.PersonaApplyConfiguration, opts v1.ApplyOptions) (result *v2.Persona, err error)
	ApplyStatus(ctx context.Context, persona *computev2.PersonaApplyConfiguration, opts v1.ApplyOptions) (result *v2.Persona, err error)
	PersonaExpansion
}

// personas implements PersonaInterface
type personas struct {
	client rest.Interface
	ns     string
}

// newPersonas returns a Personas
func newPersonas(c *ComputeV2Client, namespace string) *personas {
	return &personas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the persona, and returns the corresponding persona object, and an error if there is any.
func (c *personas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.Persona, err error) {
	result = &v2.Persona{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("personas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Personas that match those selectors.
func (c *personas) List(ctx context.Context, opts v1.ListOptions) (result *v2.PersonaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2.PersonaList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("personas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested personas.
func (c *personas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("personas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a persona and creates it.  Returns the server's representation of the persona, and an error, if there is any.
func (c *personas) Create(ctx context.Context, persona *v2.Persona, opts v1.CreateOptions) (result *v2.Persona, err error) {
	result = &v2.Persona{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("personas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(persona).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a persona and updates it. Returns the server's representation of the persona, and an error, if there is any.
func (c *personas) Update(ctx context.Context, persona *v2.Persona, opts v1.UpdateOptions) (result *v2.Persona, err error) {
	result = &v2.Persona{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("personas").
		Name(persona.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(persona).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *personas) UpdateStatus(ctx context.Context, persona *v2.Persona, opts v1.UpdateOptions) (result *v2.Persona, err error) {
	result = &v2.Persona{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("personas").
		Name(persona.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(persona).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the persona and deletes it. Returns an error if one occurs.
func (c *personas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("personas").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *personas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("personas").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched persona.
func (c *personas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.Persona, err error) {
	result = &v2.Persona{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("personas").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied persona.
func (c *personas) Apply(ctx context.Context, persona *computev2.PersonaApplyConfiguration, opts v1.ApplyOptions) (result *v2.Persona, err error) {
	if persona == nil {
		return nil, fmt.Errorf("persona provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(persona)
	if err != nil {
		return nil, err
	}
	name := persona.Name
	if name == nil {
		return nil, fmt.Errorf("persona.Name must be provided to Apply")
	}
	result = &v2.Persona{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("personas").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *personas) ApplyStatus(ctx context.Context, persona *computev2.PersonaApplyConfiguration, opts v1.ApplyOptions) (result *v2.Persona, err error) {
	if persona == nil {
		return nil, fmt.Errorf("persona provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(persona)
	if err != nil {
		return nil, err
	}

	name := persona.Name
	if name == nil {
		return nil, fmt.Errorf("persona.Name must be provided to Apply")
	}

	result = &v2.Persona{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("personas").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
