/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v2

import (
	computev2 "Persona_CRD/pkg/apis/compute/v2"
	versioned "Persona_CRD/pkg/client/clientset/versioned"
	internalinterfaces "Persona_CRD/pkg/client/informers/externalversions/internalinterfaces"
	v2 "Persona_CRD/pkg/client/listers/compute/v2"
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PersonaInformer provides access to a shared informer and lister for
// Personas.
type PersonaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v2.PersonaLister
}

type personaInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPersonaInformer constructs a new informer for Persona type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPersonaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPersonaInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPersonaInformer constructs a new informer for Persona type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPersonaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ComputeV2().Personas(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ComputeV2().Personas(namespace).Watch(context.TODO(), options)
			},
		},
		&computev2.Persona{},
		resyncPeriod,
		indexers,
	)
}

func (f *personaInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPersonaInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *personaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&computev2.Persona{}, f.defaultInformer)
}

func (f *personaInformer) Lister() v2.PersonaLister {
	return v2.NewPersonaLister(f.Informer().GetIndexer())
}
