/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "Persona_CRD/pkg/apis/compute/v2"
	computev2 "Persona_CRD/pkg/client/applyconfiguration/compute/v2"
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePersonas implements PersonaInterface
type FakePersonas struct {
	Fake *FakeComputeV2
	ns   string
}

var personasResource = v2.SchemeGroupVersion.WithResource("personas")

var personasKind = v2.SchemeGroupVersion.WithKind("Persona")

// Get takes name of the persona, and returns the corresponding persona object, and an error if there is any.
func (c *FakePersonas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.Persona, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(personasResource, c.ns, name), &v2.Persona{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Persona), err
}

// List takes label and field selectors, and returns the list of Personas that match those selectors.
func (c *FakePersonas) List(ctx context.Context, opts v1.ListOptions) (result *v2.PersonaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(personasResource, personasKind, c.ns, opts), &v2.PersonaList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2.PersonaList{ListMeta: obj.(*v2.PersonaList).ListMeta}
	for _, item := range obj.(*v2.PersonaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested personas.
func (c *FakePersonas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(personasResource, c.ns, opts))

}

// Create takes the representation of a persona and creates it.  Returns the server's representation of the persona, and an error, if there is any.
func (c *FakePersonas) Create(ctx context.Context, persona *v2.Persona, opts v1.CreateOptions) (result *v2.Persona, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(personasResource, c.ns, persona), &v2.Persona{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Persona), err
}

// Update takes the representation of a persona and updates it. Returns the server's representation of the persona, and an error, if there is any.
func (c *FakePersonas) Update(ctx context.Context, persona *v2.Persona, opts v1.UpdateOptions) (result *v2.Persona, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(personasResource, c.ns, persona), &v2.Persona{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Persona), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePersonas) UpdateStatus(ctx context.Context, persona *v2.Persona, opts v1.UpdateOptions) (*v2.Persona, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(personasResource, "status", c.ns, persona), &v2.Persona{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Persona), err
}

// Delete takes name of the persona and deletes it. Returns an error if one occurs.
func (c *FakePersonas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(personasResource, c.ns, name, opts), &v2.Persona{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePersonas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(personasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2.PersonaList{})
	return err
}

// Patch applies the patch and returns the patched persona.
func (c *FakePersonas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.Persona, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(personasResource, c.ns, name, pt, data, subresources...), &v2.Persona{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Persona), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied persona.
func (c *FakePersonas) Apply(ctx context.Context, persona *computev2.PersonaApplyConfiguration, opts v1.ApplyOptions) (result *v2.Persona, err error) {
	if persona == nil {
		return nil, fmt.Errorf("persona provided to Apply must not be nil")
	}
	data, err := json.Marshal(persona)
	if err != nil {
		return nil, err
	}
	name := persona.Name
	if name == nil {
		return nil, fmt.Errorf("persona.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(personasResource, c.ns, *name, types.ApplyPatchType, data), &v2.Persona{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Persona), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakePersonas) ApplyStatus(ctx context.Context, persona *computev2.PersonaApplyConfiguration, opts v1.ApplyOptions) (result *v2.Persona, err error) {
	if persona == nil {
		return nil, fmt.Errorf("persona provided to Apply must not be nil")
	}
	data, err := json.Marshal(persona)
	if err != nil {
		return nil, err
	}
	name := persona.Name
	if name == nil {
		return nil, fmt.Errorf("persona.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(personasResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v2.Persona{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Persona), err
}
